PACKAGE_NAME="siano_smsdvb_dkms"
PACKAGE_VERSION="1.0"
CLEAN="make clean"
MAKE[0]="make KVER=$kernelver"
# MAKE[1]="make KVER=$kernelver"
BUILT_MODULE_NAME[0]="smsmdtv"
BUILT_MODULE_NAME[1]="smsdvb"
DEST_MODULE_LOCATION[0]="/updates"
DEST_MODULE_LOCATION[1]="/updates"
AUTOINSTALL="yes"
